# Generated by Django 6.0.3 on 2026-06-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('scan_name', models.CharField(max_length=255)),
                ('modality', models.CharField(default='NCCT', max_length=20)),
                ('original_image', models.CharField(max_length=500)),
                ('mask_image', models.CharField(max_length=500)),
                ('overlay_image', models.CharField(max_length=500)),
                ('confidence', models.FloatField()),
                ('detected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
