# Generated by Django 6.0.3 on 2026-06-27 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0003_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientGuidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_plan', models.JSONField()),
                ('exercise_plan', models.JSONField()),
                ('lifestyle_plan', models.JSONField()),
                ('doctor_questions', models.JSONField()),
                ('specialist_routing', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guidance', to='segmentation.patientscan')),
            ],
        ),
    ]
