# Generated by Django 6.0.3 on 2026-06-27 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0004_patientguidance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_risk_score', models.FloatField()),
                ('cv_risk_grade', models.CharField(max_length=20)),
                ('diabetes_risk_score', models.FloatField()),
                ('diabetes_risk_grade', models.CharField(max_length=20)),
                ('stroke_risk_score', models.FloatField()),
                ('stroke_risk_grade', models.CharField(max_length=20)),
                ('detailed_metrics', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to='segmentation.patientscan')),
            ],
        ),
    ]
