# Generated by Django 6.0.3 on 2026-06-28 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0005_patientriskprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelehealthConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_doctor', models.CharField(max_length=100)),
                ('specialist_panel', models.JSONField(default=list)),
                ('status', models.CharField(default='REQUESTED', max_length=20)),
                ('clinical_notes', models.TextField(blank=True, null=True)),
                ('signed_off_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='segmentation.patientscan')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('is_doctor', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='segmentation.telehealthconsultation')),
            ],
        ),
    ]
